const eventsList = [
  {
    id: 1,
    date: "January 01, 2016",
    eventName: "",
    eventShort: "ECCV 2016 (Oral Presentation)",
    url: "",
  },
  {
    id: 2,
    date: "February 25, 2016",
    eventName: "",
    eventShort: "ACM International Conference on WSDM 2016",
    url: "",
  },
  {
    id: 3,
    date: "May 09, 2016",
    eventName: "",
    eventShort: "AAAI Conference on Artificial Intelligence 2016",
    url: "",
  },
  {
    id: 4,
    date: "July 18, 2016",
    eventName: "",
    eventShort: "IEEE TIP 2017",
    url: "",
  },
  {
    id: 5,
    date: "August 23, 2016",
    eventName: "",
    eventShort: "ECCV 2016 (Oral Presentation)",
    url: "",
  },
  {
    id: 6,
    date: "October 01, 2016",
    eventName: "",
    eventShort: "IEEE TIP 2016",
    url: "",
  },
  {
    id: 7,
    date: "November 17, 2016",
    eventName: "",
    eventShort: "BMVC 2017 (Oral Presentation)",
    url: "",
  },
  {
    id: 8,
    date: "March 07, 2017",
    eventName: "",
    eventShort: "ICCV 2017",
    url: "",
  },
  {
    id: 9,
    date: "April 12, 2017",
    eventName: "",
    eventShort: "CVPR 2017",
    url: "",
  },
  {
    id: 10,
    date: "April 13, 2017",
    eventName: "",
    eventShort: "ICLR 2017",
    url: "",
  },
  {
    id: 11,
    date: "April 19, 2017",
    eventName: "",
    eventShort: "IJCAI 2017",
    url: "",
  },
  {
    id: 12,
    date: "August 07, 2017",
    eventName: "",
    eventShort: "CVPR 2017",
    url: "",
  },
  {
    id: 13,
    date: "August 12, 2017",
    eventName: "",
    eventShort: "UAI 2017",
    url: "",
  },
  {
    id: 14,
    date: "August 20, 2017",
    eventName: "",
    eventShort: "Interspeech 2017",
    url: "",
  },
  {
    id: 15,
    date: "September 04, 2017",
    eventName: "",
    eventShort: "BMVC 2017 (Oral Presentation)",
    url: "",
  },
  {
    id: 16,
    date: "September 05, 2017",
    eventName: "",
    eventShort:
      "ICML 2016 (Workshops on Advances in Non-convex Analysis and Optimization)",
    url: "",
  },
  {
    id: 17,
    date: "September 11, 2017",
    eventName: "",
    eventShort:
      "IEEE Transactions on Pattern Analysis and Machine Intelligence, 2017",
    url: "",
  },
  {
    id: 18,
    date: "November 01, 2017",
    eventName: "",
    eventShort: "ACM Transactions on Graphics (SIGGRAPH Asia 2017)",
    url: "",
  },
  {
    id: 19,
    date: "November 30, 2017",
    eventName: "",
    eventShort: "NIPS Workshops, 2017",
    url: "",
  },
  {
    id: 20,
    date: "December 04, 2017",
    eventName: "",
    eventShort: "NIPS 2017 (Workshop Optimization for Machine Learning (OPT))",
    url: "",
  },
  { id: 21, date: "", eventName: "", eventShort: "", url: "" },
  { id: 22, date: "", eventName: "", eventShort: "", url: "" },
  { id: 23, date: "", eventName: "", eventShort: "", url: "" },
  { id: 24, date: "", eventName: "", eventShort: "", url: "" },
  { id: 25, date: "", eventName: "", eventShort: "", url: "" },
  { id: 26, date: "", eventName: "", eventShort: "", url: "" },
  { id: 27, date: "", eventName: "", eventShort: "", url: "" },
  { id: 28, date: "", eventName: "", eventShort: "", url: "" },
  { id: 29, date: "", eventName: "", eventShort: "", url: "" },
  { id: 30, date: "", eventName: "", eventShort: "", url: "" },
  { id: 31, date: "", eventName: "", eventShort: "", url: "" },
  { id: 32, date: "", eventName: "", eventShort: "", url: "" },
  { id: 33, date: "", eventName: "", eventShort: "", url: "" },
  { id: 34, date: "", eventName: "", eventShort: "", url: "" },
  { id: 35, date: "", eventName: "", eventShort: "", url: "" },
  { id: 36, date: "", eventName: "", eventShort: "", url: "" },
  { id: 37, date: "", eventName: "", eventShort: "", url: "" },
  { id: 38, date: "", eventName: "", eventShort: "", url: "" },
  { id: 39, date: "", eventName: "", eventShort: "", url: "" },
  { id: 40, date: "", eventName: "", eventShort: "", url: "" },
  { id: 41, date: "", eventName: "", eventShort: "", url: "" },
  { id: 42, date: "", eventName: "", eventShort: "", url: "" },
  { id: 43, date: "", eventName: "", eventShort: "", url: "" },
  { id: 44, date: "", eventName: "", eventShort: "", url: "" },
  { id: 45, date: "", eventName: "", eventShort: "", url: "" },
  { id: 46, date: "", eventName: "", eventShort: "", url: "" },
  { id: 47, date: "", eventName: "", eventShort: "", url: "" },
  { id: 48, date: "", eventName: "", eventShort: "", url: "" },
  { id: 49, date: "", eventName: "", eventShort: "", url: "" },
  { id: 50, date: "", eventName: "", eventShort: "", url: "" },
  { id: 51, date: "", eventName: "", eventShort: "", url: "" },
  { id: 52, date: "", eventName: "", eventShort: "", url: "" },
  { id: 53, date: "", eventName: "", eventShort: "", url: "" },
  { id: 54, date: "", eventName: "", eventShort: "", url: "" },
  { id: 55, date: "", eventName: "", eventShort: "", url: "" },
  { id: 56, date: "", eventName: "", eventShort: "", url: "" },
  { id: 57, date: "", eventName: "", eventShort: "", url: "" },
  { id: 58, date: "", eventName: "", eventShort: "", url: "" },
  { id: 59, date: "", eventName: "", eventShort: "", url: "" },
  { id: 60, date: "", eventName: "", eventShort: "", url: "" },
  { id: 61, date: "", eventName: "", eventShort: "", url: "" },
  { id: 62, date: "", eventName: "", eventShort: "", url: "" },
  { id: 63, date: "", eventName: "", eventShort: "", url: "" },
  { id: 64, date: "", eventName: "", eventShort: "", url: "" },
  { id: 65, date: "", eventName: "", eventShort: "", url: "" },
  { id: 66, date: "", eventName: "", eventShort: "", url: "" },
  { id: 67, date: "", eventName: "", eventShort: "", url: "" },
  { id: 68, date: "", eventName: "", eventShort: "", url: "" },
  { id: 69, date: "", eventName: "", eventShort: "", url: "" },
  { id: 70, date: "", eventName: "", eventShort: "", url: "" },
  { id: 71, date: "", eventName: "", eventShort: "", url: "" },
  { id: 72, date: "", eventName: "", eventShort: "", url: "" },
  { id: 73, date: "", eventName: "", eventShort: "", url: "" },
  { id: 74, date: "", eventName: "", eventShort: "", url: "" },
  { id: 75, date: "", eventName: "", eventShort: "", url: "" },
  { id: 76, date: "", eventName: "", eventShort: "", url: "" },
  { id: 77, date: "", eventName: "", eventShort: "", url: "" },
  { id: 78, date: "", eventName: "", eventShort: "", url: "" },
  { id: 79, date: "", eventName: "", eventShort: "", url: "" },
  { id: 80, date: "", eventName: "", eventShort: "", url: "" },
  { id: 81, date: "", eventName: "", eventShort: "", url: "" },
  { id: 82, date: "", eventName: "", eventShort: "", url: "" },
  { id: 83, date: "", eventName: "", eventShort: "", url: "" },
  { id: 84, date: "", eventName: "", eventShort: "", url: "" },
  { id: 85, date: "", eventName: "", eventShort: "", url: "" },
  { id: 86, date: "", eventName: "", eventShort: "", url: "" },
  { id: 87, date: "", eventName: "", eventShort: "", url: "" },
  { id: 88, date: "", eventName: "", eventShort: "", url: "" },
  { id: 89, date: "", eventName: "", eventShort: "", url: "" },
  { id: 90, date: "", eventName: "", eventShort: "", url: "" },
  { id: 91, date: "", eventName: "", eventShort: "", url: "" },
  { id: 92, date: "", eventName: "", eventShort: "", url: "" },
  { id: 93, date: "", eventName: "", eventShort: "", url: "" },
  { id: 94, date: "", eventName: "", eventShort: "", url: "" },
  { id: 95, date: "", eventName: "", eventShort: "", url: "" },
  { id: 96, date: "", eventName: "", eventShort: "", url: "" },
  { id: 97, date: "", eventName: "", eventShort: "", url: "" },
  { id: 98, date: "", eventName: "", eventShort: "", url: "" },
];

function getEvents() {
  const tempEventList = eventsList.map((item) => {
    tempItem = { ...item };
    const { date } = tempItem;
    const [month, day, year] = date.split(" ");
    tempItem.month = month.slice(0, 3).toUpperCase();
    tempItem.day = parseInt(day);
    tempItem.year = +year;
    return tempItem;
  });
  return tempEventList.sort((a, b) => {
    return new Date(b.date) - new Date(a.date);
  });
}
